# Generated by Django 4.1.4 on 2022-12-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalConfirmed', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
            ],
        ),
    ]
