# Generated by Django 4.1.4 on 2022-12-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19statistics', '0003_sumarystatistics_delete_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=30)),
                ('TotalConfirmed', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='SumaryStatistics',
        ),
    ]
