# Generated by Django 4.1.4 on 2022-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19statistics', '0004_allrecords_delete_sumarystatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecords',
            name='Country',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
